In [13]:
import pandas as pd
import zipfile

zip_path = r"C:\Users\MEENUACHU\Downloads\archive.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    with zip_ref.open('incident_event_log.csv') as file:
        df = pd.read_csv(file)

print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Dataset shape: (141712, 36)

Columns:
['number', 'incident_state', 'active', 'reassignment_count', 'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by', 'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by', 'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory', 'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority', 'assignment_group', 'assigned_to', 'knowledge', 'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor', 'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at']

First 5 rows:

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

In [15]:
print("Unique incidents:", df["number"].nunique())

print("\nIncident states:")
print(df["incident_state"].value_counts())

print("\nSLA values:")
print(df["made_sla"].value_counts())

print("\nDuplicate rows:", df.duplicated().sum())

Unique incidents: 24918

Incident states:
incident_state
Active                38716
New                   36407
Resolved              25751
Closed                24985
Awaiting User Info    14642
Awaiting Vendor         707
Awaiting Problem        461
Awaiting Evidence        38
-100                      5
Name: count, dtype: int64

SLA values:
made_sla
True     132497
False      9215
Name: count, dtype: int64

Duplicate rows: 0

In [17]:
print("Rows per incident:")
print(df.groupby("number").size().describe())

Rows per incident:
count    24918.000000
mean         5.687134
std          3.677845
min          2.000000
25%          3.000000
50%          5.000000
75%          7.000000
max         58.000000
dtype: float64

In [19]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print("Columns with missing values:")
print(missing)

Columns with missing values:
Series([], dtype: int64)

In [21]:
print("Question-mark values by column:")

question_marks = (df == "?").sum()

print(question_marks[question_marks > 0].sort_values(ascending=False))

Question-mark values by column:
caused_by           141689
vendor              141468
cmdb_ci             141267
rfc                 140721
problem_id          139417
sys_created_by       53076
sys_created_at       53076
u_symptom            32964
assigned_to          27496
assignment_group     14213
opened_by             4835
resolved_at           3141
closed_code            714
resolved_by            226
subcategory            111
category                78
location                76
caller_id               29
dtype: int64

In [23]:
# Replace "?" with proper missing values
df = df.replace("?", pd.NA)

print("Missing values after conversion:")
missing = df.isna().sum()
print(missing[missing > 0].sort_values(ascending=False))

Missing values after conversion:
caused_by           141689
vendor              141468
cmdb_ci             141267
rfc                 140721
problem_id          139417
sys_created_by       53076
sys_created_at       53076
u_symptom            32964
assigned_to          27496
assignment_group     14213
opened_by             4835
resolved_at           3141
closed_code            714
resolved_by            226
subcategory            111
category                78
location                76
caller_id               29
dtype: int64

In [25]:
# Missing percentage
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False)

print("Missing percentage by column:")
print(missing_pct[missing_pct > 0])

Missing percentage by column:
caused_by           99.983770
vendor              99.827820
cmdb_ci             99.685983
rfc                 99.300694
problem_id          98.380518
sys_created_at      37.453427
sys_created_by      37.453427
u_symptom           23.261262
assigned_to         19.402732
assignment_group    10.029496
opened_by            3.411849
resolved_at          2.216467
closed_code          0.503839
resolved_by          0.159478
subcategory          0.078328
category             0.055041
location             0.053630
caller_id            0.020464
dtype: float64

In [27]:
print(df.dtypes)

number                     object
incident_state             object
active                       bool
reassignment_count          int64
reopen_count                int64
sys_mod_count               int64
made_sla                     bool
caller_id                  object
opened_by                  object
opened_at                  object
sys_created_by             object
sys_created_at             object
sys_updated_by             object
sys_updated_at             object
contact_type               object
location                   object
category                   object
subcategory                object
u_symptom                  object
cmdb_ci                    object
impact                     object
urgency                    object
priority                   object
assignment_group           object
assigned_to                object
knowledge                    bool
u_priority_confirmation      bool
notify                     object
problem_id                 object
rfc                        object
vendor                     object
caused_by                  object
closed_code                object
resolved_by                object
resolved_at                object
closed_at                  object
dtype: object

In [29]:
# Columns with more than 90% missing values
high_missing_cols = [
    "caused_by",
    "vendor",
    "cmdb_ci",
    "rfc",
    "problem_id"
]

df = df.drop(columns=high_missing_cols)

print("Removed columns:")
print(high_missing_cols)

print("\nNew dataset shape:", df.shape)

Removed columns:
['caused_by', 'vendor', 'cmdb_ci', 'rfc', 'problem_id']

New dataset shape: (141712, 31)

In [31]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].nunique(dropna=True))
    print(df[col].value_counts(dropna=False).head(10))

--- number ---
Unique values: 24918
number
INC0019396    58
INC0044260    56
INC0005927    46
INC0020718    45
INC0011206    44
INC0025734    43
INC0007349    43
INC0012815    40
INC0003419    38
INC0032450    38
Name: count, dtype: int64

--- incident_state ---
Unique values: 9
incident_state
Active                38716
New                   36407
Resolved              25751
Closed                24985
Awaiting User Info    14642
Awaiting Vendor         707
Awaiting Problem        461
Awaiting Evidence        38
-100                      5
Name: count, dtype: int64

--- caller_id ---
Unique values: 5244
caller_id
Caller 1904    1425
Caller 290      791
Caller 4514     716
Caller 1441     322
Caller 298      293
Caller 3763     270
Caller 93       239
Caller 1531     231
Caller 4414     224
Caller 3160     220
Name: count, dtype: int64

--- opened_by ---
Unique values: 207
opened_by
Opened by  17     41466
Opened by  24      8063
Opened by  131     7269
Opened by  108     6121
Opened by  55      5655
Opened by  40      4915
<NA>               4835
Opened by  62      4821
Opened by  59      4657
Opened by  501     4178
Name: count, dtype: int64

--- opened_at ---
Unique values: 19849
opened_at
14/4/2016 20:42    58
4/7/2016 14:38     56
7/3/2016 11:58     52
7/3/2016 09:11     52
9/3/2016 16:03     51
7/3/2016 11:04     51
30/3/2016 09:20    51
4/3/2016 10:28     48
6/4/2016 15:09     48
7/3/2016 09:25     48
Name: count, dtype: int64

--- sys_created_by ---
Unique values: 185
sys_created_by
<NA>              53076
Created by 10     24223
Created by 13      4511
Created by 62      3943
Created by 52      3551
Created by 34      3468
Created by 20      3364
Created by 30      3347
Created by 89      3134
Created by 216     2835
Name: count, dtype: int64

--- sys_created_at ---
Unique values: 11552
sys_created_at
<NA>               53076
4/7/2016 14:50        56
15/3/2016 15:19       52
24/5/2016 09:14       47
19/4/2016 11:32       47
4/3/2016 10:31        46
10/3/2016 09:39       44
7/3/2016 10:40        41
23/3/2016 08:57       41
3/3/2016 16:23        41
Name: count, dtype: int64

--- sys_updated_by ---
Unique values: 846
sys_updated_by
Updated by 908    36162
Updated by 44     12644
Updated by 60      7009
Updated by 429     4169
Updated by 859     2560
Updated by 135     2329
Updated by 131     2224
Updated by 265     2200
Updated by 241     1902
Updated by 573     1895
Name: count, dtype: int64

--- sys_updated_at ---
Unique values: 50664
sys_updated_at
24/3/2016 18:40    420
24/3/2016 19:00    405
24/3/2016 18:51    400
24/3/2016 19:01    393
24/3/2016 18:41    386
24/3/2016 18:50    369
24/3/2016 18:59    348
24/3/2016 19:02    270
23/5/2016 11:07    214
24/3/2016 18:52    140
Name: count, dtype: int64

--- contact_type ---
Unique values: 5
contact_type
Phone             140462
Self service         995
Email                220
IVR                   18
Direct opening        17
Name: count, dtype: int64

--- location ---
Unique values: 224
location
Location 204    31690
Location 161    22605
Location 143    19245
Location 108    12623
Location 93     11554
Location 51      8016
Location 188     2142
Location 179     1975
Location 43      1748
Location 111     1530
Name: count, dtype: int64

--- category ---
Unique values: 58
category
Category 26    18453
Category 42    15977
Category 53    15968
Category 46    13324
Category 23     7779
Category 9      7365
Category 32     7273
Category 37     6584
Category 57     6532
Category 20     5506
Name: count, dtype: int64

--- subcategory ---
Unique values: 254
subcategory
Subcategory 174    35785
Subcategory 223    15598
Subcategory 175    10496
Subcategory 164     7880
Subcategory 9       4124
Subcategory 275     3643
Subcategory 135     3467
Subcategory 170     3349
Subcategory 36      2917
Subcategory 75      2113
Name: count, dtype: int64

--- u_symptom ---
Unique values: 525
u_symptom
Symptom 491    51985
<NA>           32964
Symptom 534     5559
Symptom 387     2583
Symptom 4       2532
Symptom 116     2394
Symptom 532     2097
Symptom 571     1771
Symptom 494     1367
Symptom 296     1359
Name: count, dtype: int64

--- impact ---
Unique values: 3
impact
2 - Medium    134335
3 - Low         3886
1 - High        3491
Name: count, dtype: int64

--- urgency ---
Unique values: 3
urgency
2 - Medium    134094
1 - High        4020
3 - Low         3598
Name: count, dtype: int64

--- priority ---
Unique values: 4
priority
3 - Moderate    132452
4 - Low           4030
2 - High          2972
1 - Critical      2258
Name: count, dtype: int64

--- assignment_group ---
Unique values: 78
assignment_group
Group 70    43474
<NA>        14213
Group 25     7679
Group 24     6752
Group 20     6170
Group 39     4728
Group 23     4228
Group 27     3817
Group 28     3638
Group 73     3304
Name: count, dtype: int64

--- assigned_to ---
Unique values: 234
assigned_to
<NA>            27496
Resolver 17     10590
Resolver 13      8802
Resolver 194     3515
Resolver 57      3144
Resolver 69      2983
Resolver 33      2502
Resolver 115     2229
Resolver 24      2174
Resolver 249     2128
Name: count, dtype: int64

--- notify ---
Unique values: 2
notify
Do Not Notify    141593
Send Email          119
Name: count, dtype: int64

--- closed_code ---
Unique values: 17
closed_code
code 6     86583
code 7     20733
code 9     13562
code 8      5646
code 5      4469
code 1      3265
code 10     1678
code 11     1493
code 4      1139
code 16     1091
Name: count, dtype: int64

--- resolved_by ---
Unique values: 216
resolved_by
Resolved by 15     15421
Resolved by 11     12050
Resolved by 103     5360
Resolved by 177     3811
Resolved by 53      3637
Resolved by 62      3558
Resolved by 133     3086
Resolved by 166     2543
Resolved by 180     2454
Resolved by 22      2336
Name: count, dtype: int64

--- resolved_at ---
Unique values: 18505
resolved_at
<NA>               3141
3/6/2016 16:29       93
3/6/2016 16:28       85
3/6/2016 16:27       83
3/6/2016 16:31       59
12/5/2016 23:51      58
29/4/2016 09:37      57
4/8/2016 08:39       56
13/5/2016 14:55      56
15/3/2016 12:11      54
Name: count, dtype: int64

--- closed_at ---
Unique values: 2707
closed_at
24/3/2016 18:59    3324
24/3/2016 18:50    2846
24/3/2016 18:40    2808
24/3/2016 19:00    2780
24/3/2016 19:01    2044
24/3/2016 18:51    2011
24/3/2016 18:41    1876
24/3/2016 19:02    1034
23/5/2016 11:07     701
24/3/2016 18:52     528
Name: count, dtype: int64

In [33]:
# Check whether each incident has a consistent SLA outcome

sla_consistency = df.groupby("number")["made_sla"].nunique()

print("Incidents with one SLA value:",
      (sla_consistency == 1).sum())

print("Incidents with multiple SLA values:",
      (sla_consistency > 1).sum())

Incidents with one SLA value: 15804
Incidents with multiple SLA values: 9114

In [35]:
# Show incidents where SLA value changes
inconsistent_incidents = sla_consistency[sla_consistency > 1]

print(inconsistent_incidents.head(20))

number
INC0000062    2
INC0000070    2
INC0000074    2
INC0000084    2
INC0000092    2
INC0000094    2
INC0000102    2
INC0000104    2
INC0000128    2
INC0000129    2
INC0000147    2
INC0000161    2
INC0000171    2
INC0000173    2
INC0000197    2
INC0000217    2
INC0000220    2
INC0000230    2
INC0000232    2
INC0000246    2
Name: made_sla, dtype: int64

In [39]:
#Pick one incident whose SLA value changes
example_incident = inconsistent_incidents.index[0]

print("Example incident:", example_incident)

print(
    df[df["number"] == example_incident][
        ["number", "incident_state", "opened_at",
         "sys_updated_at", "made_sla"]
    ].sort_values("sys_updated_at")
)

Example incident: INC0000062
        number incident_state        opened_at   sys_updated_at  made_sla
24  INC0000062            New  29/2/2016 06:58  29/2/2016 07:26      True
25  INC0000062            New  29/2/2016 06:58  29/2/2016 07:29      True
26  INC0000062            New  29/2/2016 06:58  29/2/2016 07:34      True
27  INC0000062            New  29/2/2016 06:58  29/2/2016 11:23      True
28  INC0000062            New  29/2/2016 06:58  29/2/2016 11:28      True
29  INC0000062            New  29/2/2016 06:58  29/2/2016 15:51      True
30  INC0000062       Resolved  29/2/2016 06:58  29/2/2016 15:51      True
31  INC0000062         Closed  29/2/2016 06:58   5/3/2016 16:00     False

In [41]:
# How many incidents have each combination of SLA values?

sla_patterns = (
    df.groupby("number")["made_sla"]
      .agg(lambda x: ",".join(sorted(x.astype(str).unique())))
      .value_counts()
)

print(sla_patterns)

made_sla
True          15803
False,True     9114
False             1
Name: count, dtype: int64

In [43]:
# Sort events chronologically for each incident
df_sorted = df.sort_values(["number", "sys_updated_at"])

# Take the final event for every incident
final_events = df_sorted.groupby("number").tail(1)

print("Final incident records:", len(final_events))

print("\nFinal incident states:")
print(final_events["incident_state"].value_counts())

print("\nFinal SLA values:")
print(final_events["made_sla"].value_counts())

Final incident records: 24918

Final incident states:
incident_state
Closed                16390
Resolved               5278
Active                 1111
New                    1017
Awaiting User Info      971
Awaiting Vendor          78
Awaiting Problem         71
Awaiting Evidence         2
Name: count, dtype: int64

Final SLA values:
made_sla
True     20856
False     4062
Name: count, dtype: int64

In [45]:
# Check SLA status against the final incident state
print(
    pd.crosstab(
        final_events["incident_state"],
        final_events["made_sla"]
    )
)

made_sla            False  True
incident_state
Active                  0   1111
Awaiting Evidence       0      2
Awaiting Problem        1     70
Awaiting User Info      1    970
Awaiting Vendor         0     78
Closed               4059  12331
New                     0   1017
Resolved                1   5277

In [47]:
# Convert date columns to proper datetime format

date_columns = [
    "opened_at",
    "sys_created_at",
    "sys_updated_at",
    "resolved_at",
    "closed_at"
]

for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        format="%d/%m/%Y %H:%M",
        errors="coerce"
    )

print(df[date_columns].dtypes)

opened_at         datetime64[ns]
sys_created_at    datetime64[ns]
sys_updated_at    datetime64[ns]
resolved_at       datetime64[ns]
closed_at         datetime64[ns]
dtype: object

In [49]:
# Sort events by incident and actual datetime
df_sorted = df.sort_values(
    ["number", "sys_updated_at"]
)

# Keep the final recorded event for each incident
final_events = df_sorted.groupby("number").tail(1).copy()

print("Final incident records:", len(final_events))

print("\nFinal SLA values:")
print(final_events["made_sla"].value_counts())

Final incident records: 24918

Final SLA values:
made_sla
True     15803
False     9115
Name: count, dtype: int64

In [51]:
# Create incident-level dataset
incident_level = final_events.copy()

# Keep only features that are useful for prediction
prediction_features = [
    "number",
    "opened_at",
    "contact_type",
    "location",
    "category",
    "subcategory",
    "impact",
    "urgency",
    "priority",
    "assignment_group",
    "opened_by",
    "knowledge",
    "u_priority_confirmation",
    "notify",
    "made_sla"
]

incident_level = incident_level[prediction_features].copy()

print("Incident-level dataset shape:", incident_level.shape)

print("\nColumns:")
print(incident_level.columns.tolist())

print("\nFirst 5 rows:")
display(incident_level.head())

Incident-level dataset shape: (24918, 15)

Columns:
['number', 'opened_at', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'opened_by', 'knowledge', 'u_priority_confirmation', 'notify', 'made_sla']

First 5 rows:

,number,opened_at,contact_type,location,category,subcategory,impact,urgency,priority,assignment_group,opened_by,knowledge,u_priority_confirmation,notify,made_sla
3,INC0000045,2016-02-29 01:16:00,Phone,Location 143,Category 55,Subcategory 170,2 - Medium,2 - Medium,3 - Moderate,Group 56,Opened by 8,True,False,Do Not Notify,True
12,INC0000047,2016-02-29 04:40:00,Phone,Location 165,Category 40,Subcategory 215,2 - Medium,2 - Medium,3 - Moderate,Group 24,Opened by 397,True,False,Do Not Notify,True
19,INC0000057,2016-02-29 06:10:00,Phone,Location 204,Category 20,Subcategory 125,2 - Medium,2 - Medium,3 - Moderate,Group 70,Opened by 8,True,False,Do Not Notify,True
23,INC0000060,2016-02-29 06:38:00,Phone,Location 204,Category 9,Subcategory 97,2 - Medium,2 - Medium,3 - Moderate,Group 25,Opened by 180,True,False,Do Not Notify,True
31,INC0000062,2016-02-29 06:58:00,Phone,Location 93,Category 53,Subcategory 168,1 - High,2 - Medium,2 - High,Group 23,Opened by 180,True,False,Do Not Notify,False

In [53]:
print("SLA distribution:")
print(incident_level["made_sla"].value_counts())

print("\nSLA percentage:")
print(
    incident_level["made_sla"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

SLA distribution:
made_sla
True     15803
False     9115
Name: count, dtype: int64

SLA percentage:
made_sla
True     63.42
False    36.58
Name: proportion, dtype: float64

In [55]:
# Create time-based features

incident_level["opened_hour"] = incident_level["opened_at"].dt.hour
incident_level["opened_day"] = incident_level["opened_at"].dt.day
incident_level["opened_month"] = incident_level["opened_at"].dt.month
incident_level["opened_weekday"] = incident_level["opened_at"].dt.dayofweek

# Create a weekend indicator
incident_level["is_weekend"] = (
    incident_level["opened_weekday"] >= 5
).astype(int)

print(incident_level[
    [
        "opened_at",
        "opened_hour",
        "opened_day",
        "opened_month",
        "opened_weekday",
        "is_weekend"
    ]
].head())

             opened_at  opened_hour  opened_day  opened_month  opened_weekday  \
3  2016-02-29 01:16:00            1          29             2               0
12 2016-02-29 04:40:00            4          29             2               0
19 2016-02-29 06:10:00            6          29             2               0
23 2016-02-29 06:38:00            6          29             2               0
31 2016-02-29 06:58:00            6          29             2               0

    is_weekend
3            0
12           0
19           0
23           0
31           0

In [57]:
print("Dataset shape:", incident_level.shape)

print("\nMissing values:")
print(
    incident_level.isna()
    .sum()
    .sort_values(ascending=False)
    .head(15)
)

Dataset shape: (24918, 20)

Missing values:
assignment_group           2157
opened_by                   714
subcategory                   8
category                      7
location                      6
u_priority_confirmation       0
opened_weekday                0
opened_month                  0
opened_day                    0
opened_hour                   0
made_sla                      0
notify                        0
number                        0
knowledge                     0
opened_at                     0
dtype: int64

In [59]:
print("\nData types:")
print(incident_level.dtypes)

Data types:
number                             object
opened_at                  datetime64[ns]
contact_type                       object
location                           object
category                           object
subcategory                        object
impact                             object
urgency                            object
priority                           object
assignment_group                   object
opened_by                          object
knowledge                            bool
u_priority_confirmation              bool
notify                             object
made_sla                             bool
opened_hour                         int32
opened_day                          int32
opened_month                        int32
opened_weekday                      int32
is_weekend                          int32
dtype: object

In [61]:
# Check missing values in our ML dataset

missing = incident_level.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print("Columns with missing values:")
print(missing)

print("\nMissing percentage:")
print(
    (missing / len(incident_level) * 100)
    .round(2)
)

Columns with missing values:
assignment_group    2157
opened_by            714
subcategory            8
category               7
location               6
dtype: int64

Missing percentage:
assignment_group    8.66
opened_by           2.87
subcategory         0.03
category            0.03
location            0.02
dtype: float64

In [63]:
# Handle missing categorical values

categorical_columns = [
    "contact_type",
    "location",
    "category",
    "subcategory",
    "assignment_group",
    "opened_by",
    "impact",
    "urgency",
    "priority",
    "notify"
]

for col in categorical_columns:
    incident_level[col] = incident_level[col].fillna("Unknown")

print("Missing values after handling:")

missing_after = incident_level.isna().sum()
print(missing_after[missing_after > 0])

Missing values after handling:
Series([], dtype: int64)

In [65]:
print("Assignment group values:")
print(incident_level["assignment_group"].value_counts().head(10))

Assignment group values:
assignment_group
Group 70    9444
Unknown     2157
Group 25    1243
Group 39    1199
Group 24    1060
Group 23     811
Group 64     716
Group 73     576
Group 28     545
Group 27     518
Name: count, dtype: int64

In [67]:
# Prepare features and target

X = incident_level.drop(
    columns=["number", "opened_at", "made_sla"]
)

y = incident_level["made_sla"].astype(int)

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget distribution:")
print(y.value_counts())

Feature shape: (24918, 17)
Target shape: (24918,)

Features:
['contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'opened_by', 'knowledge', 'u_priority_confirmation', 'notify', 'opened_hour', 'opened_day', 'opened_month', 'opened_weekday', 'is_weekend']

Target distribution:
made_sla
1    15803
0     9115
Name: count, dtype: int64

In [69]:
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training data: (19934, 17)
Testing data: (4984, 17)

Training target distribution:
made_sla
1    12642
0     7292
Name: count, dtype: int64

Testing target distribution:
made_sla
1    3161
0    1823
Name: count, dtype: int64

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = [
    "contact_type",
    "location",
    "category",
    "subcategory",
    "impact",
    "urgency",
    "priority",
    "assignment_group",
    "opened_by",
    "notify"
]

numerical_features = [
    "knowledge",
    "u_priority_confirmation",
    "opened_hour",
    "opened_day",
    "opened_month",
    "opened_weekday",
    "is_weekend"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            ),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numerical_features
        )
    ]
)

print("Preprocessor created successfully.")

Preprocessor created successfully.

In [73]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# Combine preprocessing and model
rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", rf_model)
    ]
)

# Train the model
rf_pipeline.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!

In [75]:
# Predict SLA outcome for the unseen test data

y_pred = rf_pipeline.predict(X_test)

print("First 20 predictions:")
print(y_pred[:20])

print("\nActual values:")
print(y_test.iloc[:20].values)

First 20 predictions:
[1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1]

Actual values:
[1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1]

In [77]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Model Performance")
print("-----------------")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model Performance
-----------------
Accuracy : 0.8439
Precision: 0.8461
Recall   : 0.9215
F1 Score : 0.8822

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.71      0.77      1823
           1       0.85      0.92      0.88      3161

    accuracy                           0.84      4984
   macro avg       0.84      0.82      0.83      4984
weighted avg       0.84      0.84      0.84      4984


Confusion Matrix:
[[1293  530]
 [ 248 2913]]

In [81]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=3000,
    class_weight="balanced",
    random_state=42
)

lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", lr_model)
    ]
)

lr_pipeline.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [83]:
lr_pred = lr_pipeline.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_pred)
lr_precision = precision_score(y_test, lr_pred)
lr_recall = recall_score(y_test, lr_pred)
lr_f1 = f1_score(y_test, lr_pred)

print("Logistic Regression Performance")
print("------------------------------")
print(f"Accuracy : {lr_accuracy:.4f}")
print(f"Precision: {lr_precision:.4f}")
print(f"Recall   : {lr_recall:.4f}")
print(f"F1 Score : {lr_f1:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, lr_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, lr_pred))

Logistic Regression Performance
------------------------------
Accuracy : 0.7650
Precision: 0.8464
Recall   : 0.7691
F1 Score : 0.8059

Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.76      0.70      1823
           1       0.85      0.77      0.81      3161

    accuracy                           0.77      4984
   macro avg       0.75      0.76      0.75      4984
weighted avg       0.78      0.77      0.77      4984


Confusion Matrix:
[[1382  441]
 [ 730 2431]]

In [87]:
rf_breach_prob = rf_pipeline.predict_proba(X_test)[:, 0]
lr_breach_prob = lr_pipeline.predict_proba(X_test)[:, 0]

rf_breach_auc = roc_auc_score(1 - y_test, rf_breach_prob)
lr_breach_auc = roc_auc_score(1 - y_test, lr_breach_prob)

print("ROC-AUC for SLA Breach")
print("----------------------")
print(f"Random Forest      : {rf_breach_auc:.4f}")
print(f"Logistic Regression: {lr_breach_auc:.4f}")

ROC-AUC for SLA Breach
----------------------
Random Forest      : 0.9149
Logistic Regression: 0.8539

In [89]:
# Feature importance from Random Forest

feature_names = rf_pipeline.named_steps["preprocessor"].get_feature_names_out()
importances = rf_pipeline.named_steps["model"].feature_importances_

feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(
    "importance",
    ascending=False
)

display(feature_importance.head(20))

                                      feature  importance
788                     numerical__opened_day    0.101509
789                   numerical__opened_month    0.088517
787                    numerical__opened_hour    0.065135
573    categorical__assignment_group_Group 70    0.062865
790                 numerical__opened_weekday    0.045794
785                      numerical__knowledge    0.033119
786        numerical__u_priority_confirmation    0.021068
613      categorical__opened_by_Opened by  17    0.013540
338  categorical__subcategory_Subcategory 174    0.011160
101        categorical__location_Location 204    0.011156
380  categorical__subcategory_Subcategory 223    0.010976
60         categorical__location_Location 161    0.009840
244         categorical__category_Category 42    0.009765
45         categorical__location_Location 143    0.009116
584     categorical__assignment_group_Unknown    0.009102
766      categorical__opened_by_Opened by  59    0.007684
512            categorical__priority_2 - High    0.007181
248         categorical__category_Category 46    0.007170
508             categorical__urgency_1 - High    0.007145
12         categorical__location_Location 108    0.006999

In [95]:
# aggregate feature importance to original columns

original_features = []

for feature in feature_importance["feature"]:
    feature = feature.replace("categorical__", "")
    feature = feature.replace("numerical__", "")
    
    # Match against our actual original feature names
    matched = None
    
    for col in X.columns:
        if feature == col or feature.startswith(col + "_"):
            matched = col
            break
    
    original_features.append(matched)

feature_importance["original_feature"] = original_features

aggregated_importance = (
    feature_importance
    .groupby("original_feature")["importance"]
    .sum()
    .sort_values(ascending=False)
)

print(" Aggregated Feature Importance")
print("----------------------------------------")
display(aggregated_importance.to_frame("importance"))

 Aggregated Feature Importance
----------------------------------------

                         importance
original_feature
assignment_group           0.166618
opened_by                  0.128951
subcategory                0.106219
location                   0.104328
opened_day                 0.101509
category                   0.089491
opened_month               0.088517
opened_hour                0.065135
opened_weekday             0.045794
knowledge                  0.033119
u_priority_confirmation    0.021068
priority                   0.017837
urgency                    0.012973
impact                     0.012052
is_weekend                 0.003696
contact_type               0.002053
notify                     0.000639

In [97]:
# Create first-event and final-event datasets

# First event = information available at the beginning of the incident
first_events = (
    df.sort_values(["number", "sys_updated_at"])
      .groupby("number")
      .head(1)
      .copy()
)

# Final event = final SLA outcome
final_events = (
    df.sort_values(["number", "sys_updated_at"])
      .groupby("number")
      .tail(1)
      .copy()
)

print("First-event records:", len(first_events))
print("Final-event records:", len(final_events))

First-event records: 24918
Final-event records: 24918

In [99]:
# Features available at the beginning of the incident

prediction_features = [
    "number",
    "opened_at",
    "contact_type",
    "location",
    "category",
    "subcategory",
    "impact",
    "urgency",
    "priority",
    "assignment_group",
    "opened_by",
    "knowledge",
    "u_priority_confirmation",
    "notify"
]

first_features = first_events[prediction_features].copy()

# Final SLA outcome
final_target = final_events[
    ["number", "made_sla"]
].copy()

# Merge first-event features with final SLA outcome
incident_prediction = first_features.merge(
    final_target,
    on="number",
    how="inner"
)

print("Prediction dataset shape:", incident_prediction.shape)

print("\nSLA distribution:")
print(incident_prediction["made_sla"].value_counts())

print("\nMissing values:")
print(
    incident_prediction.isnull().sum()[
        incident_prediction.isnull().sum() > 0
    ]
)

Prediction dataset shape: (24918, 15)

SLA distribution:
made_sla
True     15803
False     9115
Name: count, dtype: int64

Missing values:
location             52
category             39
subcategory          69
assignment_group    906
opened_by           714
dtype: int64

In [101]:
# Fill missing categorical values

categorical_columns = [
    "contact_type",
    "location",
    "category",
    "subcategory",
    "assignment_group",
    "opened_by",
    "impact",
    "urgency",
    "priority",
    "notify"
]

for col in categorical_columns:
    incident_prediction[col] = incident_prediction[col].fillna("Unknown")


# Create time-based features from the incident opening time

incident_prediction["opened_hour"] = (
    incident_prediction["opened_at"].dt.hour
)

incident_prediction["opened_day"] = (
    incident_prediction["opened_at"].dt.day
)

incident_prediction["opened_month"] = (
    incident_prediction["opened_at"].dt.month
)

incident_prediction["opened_weekday"] = (
    incident_prediction["opened_at"].dt.dayofweek
)

incident_prediction["is_weekend"] = (
    incident_prediction["opened_weekday"] >= 5
).astype(int)


print("Dataset shape:", incident_prediction.shape)

print("\nMissing values after cleaning:")
print(
    incident_prediction.isnull().sum()[
        incident_prediction.isnull().sum() > 0
    ]
)

print("\nColumns:")
print(incident_prediction.columns.tolist())

Dataset shape: (24918, 20)

Missing values after cleaning:
Series([], dtype: int64)

Columns:
['number', 'opened_at', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'opened_by', 'knowledge', 'u_priority_confirmation', 'notify', 'made_sla', 'opened_hour', 'opened_day', 'opened_month', 'opened_weekday', 'is_weekend']

In [103]:
# Create model features and target

X = incident_prediction.drop(
    columns=["number", "opened_at", "made_sla"]
)

y = incident_prediction["made_sla"].astype(int)

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget distribution:")
print(y.value_counts())

Feature shape: (24918, 17)
Target shape: (24918,)

Features:
['contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'opened_by', 'knowledge', 'u_priority_confirmation', 'notify', 'opened_hour', 'opened_day', 'opened_month', 'opened_weekday', 'is_weekend']

Target distribution:
made_sla
1    15803
0     9115
Name: count, dtype: int64

In [105]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training data: (19934, 17)
Testing data: (4984, 17)

Training target distribution:
made_sla
1    12642
0     7292
Name: count, dtype: int64

Testing target distribution:
made_sla
1    3161
0    1823
Name: count, dtype: int64

In [107]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Categorical features
categorical_features = [
    "contact_type",
    "location",
    "category",
    "subcategory",
    "impact",
    "urgency",
    "priority",
    "assignment_group",
    "opened_by",
    "notify"
]

# Numerical features
numerical_features = [
    "knowledge",
    "u_priority_confirmation",
    "opened_hour",
    "opened_day",
    "opened_month",
    "opened_weekday",
    "is_weekend"
]

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            ),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numerical_features
        )
    ]
)

print("Preprocessor created successfully.")
print("\nCategorical features:", len(categorical_features))
print("Numerical features:", len(numerical_features))

Preprocessor created successfully.

Categorical features: 10
Numerical features: 7

In [109]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

rf_model_corrected = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_pipeline_corrected = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", rf_model_corrected)
    ]
)

rf_pipeline_corrected.fit(X_train, y_train)

print("Corrected Random Forest trained successfully.")

Corrected Random Forest trained successfully.

In [111]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

# Predictions
y_pred_corrected = rf_pipeline_corrected.predict(X_test)

# Probability of SLA breach (class 0)
y_prob_breach_corrected = (
    rf_pipeline_corrected.predict_proba(X_test)[:, 0]
)

# Metrics
accuracy = accuracy_score(y_test, y_pred_corrected)
precision = precision_score(y_test, y_pred_corrected)
recall = recall_score(y_test, y_pred_corrected)
f1 = f1_score(y_test, y_pred_corrected)

# Breach-focused ROC-AUC
breach_auc = roc_auc_score(
    1 - y_test,
    y_prob_breach_corrected
)

print("Corrected Random Forest Performance")
print("-----------------------------------")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {breach_auc:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred_corrected))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_corrected))

Corrected Random Forest Performance
-----------------------------------
Accuracy : 0.8104
Precision: 0.8219
Recall   : 0.8950
F1 Score : 0.8569
ROC-AUC  : 0.8764

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.66      0.72      1823
           1       0.82      0.89      0.86      3161

    accuracy                           0.81      4984
   macro avg       0.80      0.78      0.79      4984
weighted avg       0.81      0.81      0.81      4984


Confusion Matrix:
[[1210  613]
 [ 332 2829]]

In [113]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

# Probability that each incident will breach SLA
breach_prob = rf_pipeline_corrected.predict_proba(X_test)[:, 0]

threshold_results = []

for threshold in np.arange(0.20, 0.61, 0.05):
    
    predicted_breach = (breach_prob >= threshold).astype(int)
    
    actual_breach = 1 - y_test
    
    precision = precision_score(
        actual_breach,
        predicted_breach,
        zero_division=0
    )
    
    recall = recall_score(
        actual_breach,
        predicted_breach,
        zero_division=0
    )
    
    f1 = f1_score(
        actual_breach,
        predicted_breach,
        zero_division=0
    )
    
    threshold_results.append({
        "threshold": round(threshold, 2),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4)
    })

threshold_df = pd.DataFrame(threshold_results)

display(threshold_df)

   threshold  precision  recall      f1
0       0.20     0.5667  0.9133  0.6994
1       0.25     0.6005  0.8749  0.7122
2       0.30     0.6358  0.8310  0.7204
3       0.35     0.6762  0.7926  0.7298
4       0.40     0.7114  0.7477  0.7291
5       0.45     0.7589  0.7098  0.7336
6       0.50     0.7847  0.6637  0.7192
7       0.55     0.8203  0.6160  0.7036
8       0.60     0.8500  0.5749  0.6859

In [115]:
# Final breach-risk predictions using threshold = 0.45

final_threshold = 0.45

breach_probability = (
    rf_pipeline_corrected.predict_proba(X_test)[:, 0]
)

predicted_breach = (
    breach_probability >= final_threshold
).astype(int)

prediction_output = incident_prediction.loc[X_test.index].copy()

prediction_output["actual_breach"] = (
    1 - y_test
)

prediction_output["breach_probability"] = (
    breach_probability
)

prediction_output["predicted_breach"] = (
    predicted_breach
)

print("Final threshold:", final_threshold)

print("\nPrediction output shape:")
print(prediction_output.shape)

print("\nPredicted breach distribution:")
print(prediction_output["predicted_breach"].value_counts())

display(
    prediction_output[
        [
            "number",
            "priority",
            "category",
            "assignment_group",
            "actual_breach",
            "breach_probability",
            "predicted_breach"
        ]
    ].head(10)
)

Final threshold: 0.45

Prediction output shape:
(4984, 23)

Predicted breach distribution:
predicted_breach
0    3279
1    1705
Name: count, dtype: int64

,number,priority,category,assignment_group,actual_breach,breach_probability,predicted_breach
12578,INC0018420,3 - Moderate,Category 32,Group 70,0,0.000000,0
11542,INC0016988,3 - Moderate,Category 43,Group 22,0,0.272131,0
8534,INC0012846,3 - Moderate,Category 42,Group 70,0,0.040000,0
3692,INC0005908,3 - Moderate,Category 53,Group 70,1,0.710000,1
11957,INC0017577,3 - Moderate,Category 42,Group 55,0,0.082671,0
8285,INC0012506,3 - Moderate,Category 8,Group 53,1,0.543171,1
12890,INC0018858,3 - Moderate,Category 46,Group 39,0,0.255000,0
21677,INC0030428,3 - Moderate,Category 20,Group 70,0,0.040000,0
16472,INC0023620,3 - Moderate,Category 51,Group 64,0,0.000000,0
10953,INC0016197,3 - Moderate,Category 57,Group 65,1,0.562322,1

In [117]:
# Select the columns we need for the dashboard

powerbi_output = prediction_output[
    [
        "number",
        "opened_at",
        "contact_type",
        "location",
        "category",
        "subcategory",
        "impact",
        "urgency",
        "priority",
        "assignment_group",
        "opened_by",
        "knowledge",
        "u_priority_confirmation",
        "notify",
        "made_sla",
        "actual_breach",
        "breach_probability",
        "predicted_breach"
    ]
].copy()

# Rename columns to make them easier to understand in Power BI

powerbi_output = powerbi_output.rename(
    columns={
        "made_sla": "SLA_Met",
        "actual_breach": "Actual_Breach",
        "breach_probability": "Breach_Probability",
        "predicted_breach": "Predicted_Breach"
    }
)

# Save CSV

powerbi_output.to_csv(
    "opsinsight_ml_predictions.csv",
    index=False
)

print("Power BI dataset saved successfully.")
print("Shape:", powerbi_output.shape)
print("\nColumns:")
print(powerbi_output.columns.tolist())

Power BI dataset saved successfully.
Shape: (4984, 18)

Columns:
['number', 'opened_at', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'opened_by', 'knowledge', 'u_priority_confirmation', 'notify', 'SLA_Met', 'Actual_Breach', 'Breach_Probability', 'Predicted_Breach']

In [119]:
import joblib

joblib.dump(
    rf_pipeline_corrected,
    "sla_breach_model.pkl"
)

print("Model saved successfully as sla_breach_model.pkl")

Model saved successfully as sla_breach_model.pkl

In [121]:
import sqlite3

# Create SQLite database
conn = sqlite3.connect("opsinsight.db")

# Create an incident-level table
sql_df = incident_prediction.copy()

# Remove datetime column temporarily because SQLite will store it as text
sql_df["opened_at"] = sql_df["opened_at"].astype(str)

sql_df.to_sql(
    "incidents",
    conn,
    if_exists="replace",
    index=False
)

print("SQLite database created successfully.")
print("Table created: incidents")

SQLite database created successfully.
Table created: incidents

In [123]:
query = """
SELECT
    priority,
    COUNT(*) AS total_incidents,
    SUM(CASE WHEN made_sla = 1 THEN 1 ELSE 0 END) AS sla_met,
    SUM(CASE WHEN made_sla = 0 THEN 1 ELSE 0 END) AS sla_breached,
    ROUND(
        100.0 * SUM(CASE WHEN made_sla = 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS breach_rate_pct
FROM incidents
GROUP BY priority
ORDER BY breach_rate_pct DESC;
"""

result = pd.read_sql_query(query, conn)

display(result)

       priority  total_incidents  sla_met  sla_breached  breach_rate_pct
0      2 - High              311        9           302            97.11
1  1 - Critical              185       36           149            80.54
2  3 - Moderate            23681    15126          8555            36.13
3       4 - Low              741      632           109            14.71

In [125]:
query = """
WITH category_summary AS (
    SELECT
        category,
        COUNT(*) AS total_incidents,
        SUM(CASE WHEN made_sla = 0 THEN 1 ELSE 0 END) AS sla_breached
    FROM incidents
    GROUP BY category
)

SELECT
    category,
    total_incidents,
    sla_breached,
    ROUND(
        100.0 * sla_breached / total_incidents,
        2
    ) AS breach_rate_pct
FROM category_summary
WHERE total_incidents >= 100
ORDER BY breach_rate_pct DESC;
"""

result = pd.read_sql_query(query, conn)

display(result)

       category  total_incidents  sla_breached  breach_rate_pct
0   Category 45              625           478            76.48
1   Category 40              686           511            74.49
2   Category 34              498           332            66.67
3   Category 61              805           426            52.92
4   Category 44              331           167            50.45
5   Category 19              220           110            50.00
6   Category 46             2243          1114            49.67
7   Category 23             1071           509            47.53
8   Category 24              638           303            47.49
9    Category 9             1141           456            39.96
10  Category 13              119            47            39.50
11  Category 57              916           355            38.76
12  Category 43              172            66            38.37
13  Category 53             2655           985            37.10
14  Category 37             1135           373            32.86
15  Category 26             3268           945            28.92
16  Category 28              522           126            24.14
17  Category 32             1495           358            23.95
18  Category 20             1067           254            23.81
19  Category 42             3629           722            19.90
20  Category 51              545           103            18.90
21  Category 35              512            42             8.20

In [127]:
query = """
WITH category_summary AS (
    SELECT
        category,
        COUNT(*) AS total_incidents,
        SUM(CASE WHEN made_sla = 0 THEN 1 ELSE 0 END) AS sla_breached
    FROM incidents
    GROUP BY category
)

SELECT
    category,
    total_incidents,
    sla_breached,
    ROUND(
        100.0 * sla_breached / total_incidents,
        2
    ) AS breach_rate_pct,
    RANK() OVER (
        ORDER BY
            100.0 * sla_breached / total_incidents DESC
    ) AS breach_rank
FROM category_summary
WHERE total_incidents >= 100
ORDER BY breach_rank;
"""

result = pd.read_sql_query(query, conn)

display(result)

       category  total_incidents  sla_breached  breach_rate_pct  breach_rank
0   Category 45              625           478            76.48            1
1   Category 40              686           511            74.49            2
2   Category 34              498           332            66.67            3
3   Category 61              805           426            52.92            4
4   Category 44              331           167            50.45            5
5   Category 19              220           110            50.00            6
6   Category 46             2243          1114            49.67            7
7   Category 23             1071           509            47.53            8
8   Category 24              638           303            47.49            9
9    Category 9             1141           456            39.96           10
10  Category 13              119            47            39.50           11
11  Category 57              916           355            38.76           12
12  Category 43              172            66            38.37           13
13  Category 53             2655           985            37.10           14
14  Category 37             1135           373            32.86           15
15  Category 26             3268           945            28.92           16
16  Category 28              522           126            24.14           17
17  Category 32             1495           358            23.95           18
18  Category 20             1067           254            23.81           19
19  Category 42             3629           722            19.90           20
20  Category 51              545           103            18.90           21
21  Category 35              512            42             8.20           22

In [129]:
query = """
SELECT
    strftime('%Y-%m', opened_at) AS month,
    COUNT(*) AS total_incidents,
    SUM(CASE WHEN made_sla = 0 THEN 1 ELSE 0 END) AS sla_breached,
    ROUND(
        100.0 * SUM(CASE WHEN made_sla = 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS breach_rate_pct
FROM incidents
GROUP BY month
ORDER BY month;
"""

result = pd.read_sql_query(query, conn)

display(result)

      month  total_incidents  sla_breached  breach_rate_pct
0   2016-02              207            73            35.27
1   2016-03             8995          5410            60.14
2   2016-04             7934          1849            23.30
3   2016-05             7508          1688            22.48
4   2016-06                5             1            20.00
5   2016-07               14             3            21.43
6   2016-08               15             8            53.33
7   2016-09               12             5            41.67
8   2016-10               16             9            56.25
9   2016-11               26             9            34.62
10  2016-12               37            14            37.84
11  2017-01               94            41            43.62
12  2017-02               55             5             9.09

In [131]:
# Create the complete incident-level dataset for Power BI

powerbi_incidents = incident_prediction.copy()

powerbi_incidents = powerbi_incidents.rename(
    columns={
        "number": "Incident_ID",
        "opened_at": "Opened_At",
        "made_sla": "SLA_Met"
    }
)

powerbi_incidents.to_csv(
    "opsinsight_incidents.csv",
    index=False
)

print("Power BI incident dataset saved successfully.")
print("Shape:", powerbi_incidents.shape)
print("\nColumns:")
print(powerbi_incidents.columns.tolist())

Power BI incident dataset saved successfully.
Shape: (24918, 20)

Columns:
['Incident_ID', 'Opened_At', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'opened_by', 'knowledge', 'u_priority_confirmation', 'notify', 'SLA_Met', 'opened_hour', 'opened_day', 'opened_month', 'opened_weekday', 'is_weekend']